### ISSUE TITLE
At the moment, does WebAssembly has GC implemented?

### ISSUE THREAD

**Issue by evertondanilo** [WebAssembly/proposals#101]
Based on the docs here, I think GC is in the specification phase. However, as Microsoft has released Blazor WebAssembly, I think that WA has some GC already implemented. Am I right? What GC features does WASM already have?

**Comment by dschuff** [comment]
I think Blazor is allocating their objects in wasm's linear memory, and then their GC scans inside the linear memory for pointers and frees them. The GC proposal is for objects outside the linear memory (managed by the VM that's running the wasm code, rather than the one running as compiled wasm code). on JS engines, these objects would be alongside the JS objects and be managed by the same GC.

**Comment by protheory8** [comment]
@evertondanilo No, C# ships and uses their own GC.

**Comment by tlively** [comment]
Closing this issue because the question has been answered.
